### ISSUE TITLE
Infinite loop when querying non-existing Runtime API with the Reconnecting Client

### ISSUE THREAD

**Issue by pgherveou** [paritytech/subxt#1903]
We have this piece of code here that calls a runtime_api with subxt

https://github.com/paritytech/polkadot-sdk/blob/e9393a9afc3b33cc2d01b7820a8f186434196758/substrate/frame/revive/rpc/src/client.rs#L696-L703

When called for a block that pre-date this Runtime API, it looks like subxt enter in an infite loop

```log
2025-01-24 10:00:02.145 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":184,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
2025-01-24 10:00:02.179 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":185,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
2025-01-24 10:00:02.211 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":186,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
2025-01-24 10:00:02.244 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":187,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
2025-01-24 10:00:02.278 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":188,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
2025-01-24 10:00:02.322 TRACE tokio-runtime-worker jsonrpsee-client: send="{\"jsonrpc\":\"2.0\",\"id\":189,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"
```

This can be tested with the following command from the polkadot-sdk repo

```sh
RUST_LOG="jsonrpsee=trace,subxt=trace,info,eth-rpc=debug" cargo run -p pallet-revive-eth-rpc -- --dev --node-rpc-url "wss://westend-asset-hub-rpc.polkadot.io"
```

Then hit the server with the following curl

```sh
curl --verbose  -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0",false],"id":43}' http://localhost:8545
```

The substrate node request return the expected response

```sh
curl https://westend-asset-hub-rpc.polkadot.io \
--header 'Content-Type: application/json' \
--data "{\"jsonrpc\":\"2.0\",\"id\":189,\"method\":\"state_call\",\"params\":[\"ReviveApi_block_gas_limit\",\"0x\",\"0x67f9723393ef76214df0118c34bbbd3dbebc8ed46a10973a8c969d48fe7598c9\"]}"


{
  "jsonrpc": "2.0",
  "id": 189,
  "error": {
    "code": 4003,
    "message": "Client error: Execution failed: Other: Exported method ReviveApi_block_gas_limit is not found"
  }
}
```

**Comment by pgherveou** [comment]
Issue seems to be related to the fact that we are using the reconnecting client

**Comment by pgherveou** [comment]
Repro repo https://github.com/pgherveou/subxt-playground

**Comment by jsdw** [comment]
Should be fixed by https://github.com/paritytech/subxt/pull/1904

**Comment by nhussein11** [comment]
@pgherveou Does this need to be deployed to "wss://westend-asset-hub-rpc.polkadot.io"? I'm still encountering the same issue here

**Comment by jsdw** [comment]
> @pgherveou Does this need to be deployed to "wss://westend-asset-hub-rpc.polkadot.io"? I'm still encountering the same issue here

We are doing a Subxt release shortly and then I expect @pgherveou can handle this side of it :)

**Comment by nhussein11** [comment]
Thanks, @jsdw! @pgherveou, could you please ping me when this is finished?

**Comment by jsdw** [comment]
Just FYI the 0.38.1 release was done so this should be unblocked from the Subxt side. Let us know if any issues!
