### ISSUE TITLE
Extrinsic construction should default to `Era::mortal` 

### ISSUE THREAD

**Issue by emostov** [paritytech/subxt#202]
Currently, it looks like extrinsic construction with `subxt` [defaults to `Era::Immortal`](https://github.com/paritytech/substrate-subxt/blob/80aff7eb6e66b4e7cdd504b385fe73ef2878894d/src/extrinsic/extra.rs#L288). Further, it looks like the `subxt` public api does not expose a way for a user to construct a mortal transaction. 

Immortal transactions are dangerous as they expose a potential replay attack vector; thus I believe defaulting to (or even only allowing) mortal transactions is best practice for an extrinsic construction lib. [Here is a section on the polkadot wiki that elaborates on the aforementioned	.](https://wiki.polkadot.network/docs/en/build-protocol-info#transaction-mortality)

If my understanding is correct, implementation wise one way to achieve this is by allowing [`Extrinsic::new()`](https://github.com/paritytech/substrate-subxt/blob/80aff7eb6e66b4e7cdd504b385fe73ef2878894d/src/extrinsic/extra.rs#L236) to accept an argument for `Era`, which could [be constructed with this](https://github.com/paritytech/substrate/blob/dbf2163250833e6ac898e7f6c3c8f89f08a7c19d/primitives/runtime/src/generic/era.rs#L66) - passing in `current` block number, and `period` blocks the transaction should live for, with a reasonable default like 64. `current` block number could be fetched under the hood by RPC and `period` could be filled by a default value, which I think would result in no breaking changes for current users (not counting the change that the ext is now mortal).

cc @dvdplm, @joepetrowski

**Comment by dvdplm** [comment]
cc @ascjones

I believe we have a PR forthcoming in this sense. :)

**Comment by niklasad1** [comment]
This is fixed a long time ago, closing

**Comment by JesseAbram** [comment]
We use subxt in entropy and I was reading through the code, and I don't think this is fixed. Just looking here at the [default](https://github.com/paritytech/subxt/blob/master/subxt/src/config/default_extrinsic_params.rs#L48) it is None then on build it would be set to [immortal](https://github.com/paritytech/subxt/blob/master/subxt/src/config/default_extrinsic_params.rs#L122).  This is called in ```sign_submit_and_watch_default``` [here](https://github.com/paritytech/subxt/blob/master/subxt/src/tx/tx_client.rs#L218) which is referenced multiple times in the example code

**Comment by jsdw** [comment]
Indeed, we don't default to `Era::mortal` at the moment. It's a bit tricky for us to do for a couple of reasons:
- You need to provide a block hash from which an extrinsic is valid (though I suspect Subxt could handle that bit without issue), and
- Subxt is generic over exactly which signed extensions (and thus parameters to configure them) are configured for a chain.

It's probably something that can be addressed with some thought. I think this issue was closed because it never actually used to be possible to define a mortal extrinsic at all, which is possible now (see this exampel if you'd like to know how: https://github.com/paritytech/subxt/blob/master/subxt/examples/tx_with_params.rs)

**Comment by JesseAbram** [comment]
mmm yes that makes sense, it came up in a PR when I was like ooo im sending immortal tx, and I definitely don't have enough vision for how subxt is used (we use it online so from my perspective this is easy but I get how others would not be). Maybe and again if it doesn't make sense but the default should default to a mortal tx of 32 for safety and if you want to use it offline or in another way you need to specify that it be immortal, for safety issues, but if that doesn't make sense no worries.

**Comment by jsdw** [comment]
I agree that mortal extrinsics is definitely a better default; let's re-open this issue and we can think about how that might be possible to achieve!

**Comment by jsdw** [comment]
We actually finally worked out how to do this in #1432, so from that PR onwards extrinsics will have a default mortality (iirc 32 blocks) unless explicitly configured by the user to be something different :)
